name: Scrape New Cellular Devices

on:
  schedule:
    - cron: '30 23 * * *'  # 5 AM IST
    - cron: '30 0 * * *'   # 6 AM IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run scraper script
        run: python scrape_devices.py > output.json

      - name: Commit results if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output.json
          git commit -m "Update scraped devices $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📱 NBTC Scraper Run Complete!
            Found new devices: Check the output file or logs for details.
            Run link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            (If no new devices, output might be empty.)
