name: NBTC Device Monitor

on:
  schedule:
    # 7:00 AM IST is 1:30 AM UTC
    - cron: '30 1 * * *'
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run monitor'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write

jobs:
  monitor-devices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium
          
      - name: Run NBTC monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python nbtc_monitor.py
        
      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add any generated files
          if [ -f "seen_devices.json" ]; then
            git add seen_devices.json
            echo "✅ Added seen_devices.json"
          fi
          
          if [ -f "new_devices.json" ]; then
            git add new_devices.json
            echo "✅ Added new_devices.json"
          fi
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to commit"
          else
            git commit -m "🤖 Update device data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "✅ Changes committed and pushed"
          fi
