name: Scrape NBTC Cellular Mobile Devices

on:
  schedule:
    # 7:00 AM IST is 1:30 AM UTC
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: write  # This allows GitHub Actions to push changes

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
      - name: Run scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scrape.py
      - name: Commit results (if any)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Add files if they exist
          if [ -f "seen_devices.json" ]; then
            git add seen_devices.json
            echo "Added seen_devices.json"
          fi
          
          if [ -f "new_devices.json" ]; 
